### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by scenaristeur** [ludwigschubi/shex-codegen-demo#2]
Hi, 👋
I've tried to login but nothing happens when I click login button

![Screenshot_20210424-231408_Chrome](https://user-images.githubusercontent.com/4020744/115973127-09c97b80-a553-11eb-890b-2f15c990d6d3.jpg)

**Comment by geistinme** [comment]
@scenaristeur you wrote `solidccommunity` instead of `solidcommunity`. If you type the domain correctly it works (just tested this). Closing this issue now, thank you for trying the demo 😉

**Comment by scenaristeur** [comment]
Oh sorry, thxs
